change-biome-settings:
  default: badlands
  sand: desert
  grass_block: forest
  oak_log: forest
  spruce_log: forest
  jungle_log: forest
  birch_log: forest
  oak_leaves: forest
  spruce_leaves: forest
  jungle_leaves: forest
  birch_leaves: forest
  dirt: forest
  gravel: forest
  podzol: forest
  barrier: forest
  snow: snowy_slopes
no-firework-damage: true
no-drop-menu: true
no-destroy-painting: true
no-armourstand-manipulation: true

# composters, vases, etc
no-block-interaction: true

invulnerable-armourstand-on-spawn: true
invulnerable-painting-on-spawn: true
no-chicken-from-egg: true
no-snow-and-ice-formation: true
