api-version: 1.13
name: GameUtils
main: fun.kaituo.GameUtils
version: 1.1.1
authors: [YFshadaow, LeChocolatChaud]
commands:
  changebiome:
    description: ChangBiome
    default: op
    aliases: [cb]
  changegame:
    description: changeGame
    default: op
  placestand:
    description: place stand
    default: op
    aliases: [ps]
  rejoin:
    description: rejoin game
    default: true
  rotatable:
    description: set item frame rotatable
    default: true
    aliases: [rt]