name: Build and Deploy


on: push

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_VERSION: na
      ARTIFACT_ID: na
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: Minigames-Kaituo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          cache: maven
          overwrite-settings: false

      - name: Maven clean and install
        run: mvn clean install

      - name: Update project info to environment variables
        run: |
          echo "Project name is `mvn help:evaluate -Dexpression=project.name -q -DforceStdout`"
          echo "PROJECT_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
          echo "ARTIFACT_ID=`mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout`" >> $GITHUB_ENV

      - name: Ftp deloy to server
        env:
          FTP_SERVER: ${{secrets.FTP_SERVER}}
          FTP_PORT: ${{secrets.FTP_PORT}}
          FTP_USERNAME: ${{secrets.FTP_USERNAME}}
          FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        shell: bash
        run: |
          pftp -inv "$FTP_SERVER" "$FTP_PORT" <<EOF
          user "$FTP_USERNAME" "$FTP_PASSWORD"
          binary
          put target/"$ARTIFACT_ID"-"$PROJECT_VERSION".jar "$ARTIFACT_ID".jar
          close
          bye
          EOF